export interface Market {
  id: number;
  title: string;
  category: string;
  yesPrice: number;
  noPrice: number;
  volume: string;
  endDate: string;
  participants: number;
  icon: string;
  trend?: "up" | "down";
  priceHistory?: { time: string; yes: number; no: number }[];
  description?: string;
}

export const marketsByCategory: Record<string, Market[]> = {
  trending: [
    {
      id: 1,
      title: "Will Bitcoin reach $150,000 by end of 2026?",
      category: "Crypto",
      yesPrice: 67,
      noPrice: 33,
      volume: "$2.4M",
      endDate: "Dec 31, 2026",
      participants: 12453,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=bitcoin",
      trend: "up",
    },
    {
      id: 2,
      title: "Will Manchester City win the Premier League 2025/26?",
      category: "Sports",
      yesPrice: 72,
      noPrice: 28,
      volume: "$3.2M",
      endDate: "May 24, 2026",
      participants: 23456,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=football",
      trend: "up",
    },
    {
      id: 3,
      title: "Will Trump win the 2026 midterm elections?",
      category: "Politics",
      yesPrice: 58,
      noPrice: 42,
      volume: "$4.1M",
      endDate: "Nov 3, 2026",
      participants: 34567,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=politics",
      trend: "down",
    },
    {

      id: 4,
      title: "Will Tesla stock hit $500 in 2026?",
      category: "Business",
      yesPrice: 45,
      noPrice: 55,
      volume: "$1.9M",
      endDate: "Dec 31, 2026",
      participants: 15678,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=tesla",
      trend: "up",
    },
    {

      id: 5,
      title: "Will AI replace 50% of coding jobs by 2030?",
      category: "Tech",
      yesPrice: 38,
      noPrice: 62,
      volume: "$980K",
      endDate: "Dec 31, 2030",
      participants: 15234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=ai",
      trend: "up",
    },
    {

      id: 6,
      title: "Will SpaceX land humans on Mars by 2030?",
      category: "Tech",
      yesPrice: 23,
      noPrice: 77,
      volume: "$2.1M",
      endDate: "Dec 31, 2030",
      participants: 18765,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=spacex",
      trend: "down",
    },
  ],
  new: [
    {

      id: 7,
      title: "Will Apple release AR glasses in 2026?",
      category: "Tech",
      yesPrice: 35,
      noPrice: 65,
      volume: "$450K",
      endDate: "Dec 31, 2026",
      participants: 5234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=apple",
    },
    {

      id: 8,
      title: "Will Messi retire from international football in 2026?",
      category: "Sports",
      yesPrice: 62,
      noPrice: 38,
      volume: "$890K",
      endDate: "Dec 31, 2026",
      participants: 8901,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=messi",
    },
    {

      id: 9,
      title: "Will inflation drop below 2% in the US by Q4 2026?",
      category: "Business",
      yesPrice: 48,
      noPrice: 52,
      volume: "$1.2M",
      endDate: "Dec 31, 2026",
      participants: 11234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=inflation",
    },
    {

      id: 10,
      title: "Will Solana flip Ethereum in market cap by 2027?",
      category: "Crypto",
      yesPrice: 15,
      noPrice: 85,
      volume: "$670K",
      endDate: "Dec 31, 2027",
      participants: 9876,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=solana",
    },
    {

      id: 11,
      title: "Will renewable energy exceed 50% of US power by 2028?",
      category: "Climate",
      yesPrice: 56,
      noPrice: 44,
      volume: "$780K",
      endDate: "Dec 31, 2028",
      participants: 6543,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=renewable",
    },
    {

      id: 12,
      title: "Will ChatGPT-5 be released in 2026?",
      category: "Tech",
      yesPrice: 71,
      noPrice: 29,
      volume: "$1.5M",
      endDate: "Dec 31, 2026",
      participants: 19876,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=chatgpt",
    },
  ],
  sports: [
    {

      id: 13,
      title: "Will Manchester City win the Premier League 2025/26?",
      category: "Sports",
      yesPrice: 72,
      noPrice: 28,
      volume: "$3.2M",
      endDate: "May 24, 2026",
      participants: 23456,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=football",
    },
    {

      id: 14,
      title: "Will LeBron James retire in 2026?",
      category: "Sports",
      yesPrice: 44,
      noPrice: 56,
      volume: "$1.8M",
      endDate: "Dec 31, 2026",
      participants: 14567,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=lebron",
    },
    {

      id: 15,
      title: "Will Messi retire from international football in 2026?",
      category: "Sports",
      yesPrice: 62,
      noPrice: 38,
      volume: "$890K",
      endDate: "Dec 31, 2026",
      participants: 8901,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=messi",
    },
    {

      id: 16,
      title: "Will USA win the most medals at 2026 Winter Olympics?",
      category: "Sports",
      yesPrice: 39,
      noPrice: 61,
      volume: "$1.1M",
      endDate: "Feb 28, 2026",
      participants: 9876,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=olympics",
    },
    {

      id: 17,
      title: "Will Real Madrid win Champions League 2025/26?",
      category: "Sports",
      yesPrice: 55,
      noPrice: 45,
      volume: "$2.3M",
      endDate: "May 31, 2026",
      participants: 18234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=realmadrid",
    },
    {

      id: 18,
      title: "Will Novak Djokovic win another Grand Slam in 2026?",
      category: "Sports",
      yesPrice: 68,
      noPrice: 32,
      volume: "$1.4M",
      endDate: "Dec 31, 2026",
      participants: 11234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=djokovic",
    },
  ],
  crypto: [
    {

      id: 19,
      title: "Will Bitcoin reach $150,000 by end of 2026?",
      category: "Crypto",
      yesPrice: 67,
      noPrice: 33,
      volume: "$2.4M",
      endDate: "Dec 31, 2026",
      participants: 12453,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=bitcoin",
    },
    {

      id: 20,
      title: "Will Ethereum ETF be approved in Q1 2026?",
      category: "Crypto",
      yesPrice: 45,
      noPrice: 55,
      volume: "$1.8M",
      endDate: "Mar 31, 2026",
      participants: 8921,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=ethereum",
    },
    {

      id: 21,
      title: "Will Solana flip Ethereum in market cap by 2027?",
      category: "Crypto",
      yesPrice: 15,
      noPrice: 85,
      volume: "$670K",
      endDate: "Dec 31, 2027",
      participants: 9876,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=solana",
    },
    {

      id: 22,
      title: "Will a Bitcoin ETF reach $100B AUM in 2026?",
      category: "Crypto",
      yesPrice: 73,
      noPrice: 27,
      volume: "$1.9M",
      endDate: "Dec 31, 2026",
      participants: 15678,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=btcetf",
    },
    {

      id: 23,
      title: "Will Cardano reach $5 in 2026?",
      category: "Crypto",
      yesPrice: 22,
      noPrice: 78,
      volume: "$540K",
      endDate: "Dec 31, 2026",
      participants: 7890,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=cardano",
    },
    {

      id: 24,
      title: "Will a major country adopt Bitcoin as legal tender in 2026?",
      category: "Crypto",
      yesPrice: 31,
      noPrice: 69,
      volume: "$980K",
      endDate: "Dec 31, 2026",
      participants: 12345,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=btclegal",
    },
  ],
  politics: [
    {

      id: 25,
      title: "Will Trump win the 2026 midterm elections?",
      category: "Politics",
      yesPrice: 58,
      noPrice: 42,
      volume: "$4.1M",
      endDate: "Nov 3, 2026",
      participants: 34567,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=politics",
    },
    {

      id: 26,
      title: "Will Biden run for re-election in 2028?",
      category: "Politics",
      yesPrice: 34,
      noPrice: 66,
      volume: "$2.8M",
      endDate: "Dec 31, 2027",
      participants: 23456,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=biden",
    },
    {

      id: 27,
      title: "Will UK rejoin the EU by 2030?",
      category: "Politics",
      yesPrice: 18,
      noPrice: 82,
      volume: "$1.5M",
      endDate: "Dec 31, 2030",
      participants: 14567,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=brexit",
    },
    {

      id: 28,
      title: "Will there be a new Supreme Court justice in 2026?",
      category: "Politics",
      yesPrice: 42,
      noPrice: 58,
      volume: "$1.9M",
      endDate: "Dec 31, 2026",
      participants: 18234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=scotus",
    },
    {

      id: 29,
      title: "Will California pass universal healthcare in 2026?",
      category: "Politics",
      yesPrice: 29,
      noPrice: 71,
      volume: "$870K",
      endDate: "Dec 31, 2026",
      participants: 9876,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=healthcare",
    },
    {

      id: 30,
      title: "Will student loan forgiveness be implemented in 2026?",
      category: "Politics",
      yesPrice: 51,
      noPrice: 49,
      volume: "$2.1M",
      endDate: "Dec 31, 2026",
      participants: 21234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=studentloans",
    },
  ],
  business: [
    {

      id: 31,
      title: "Will Tesla stock hit $500 in 2026?",
      category: "Business",
      yesPrice: 45,
      noPrice: 55,
      volume: "$1.9M",
      endDate: "Dec 31, 2026",
      participants: 15678,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=tesla",
    },
    {

      id: 32,
      title: "Will the Fed cut rates in Q2 2026?",
      category: "Business",
      yesPrice: 64,
      noPrice: 36,
      volume: "$2.7M",
      endDate: "Jun 30, 2026",
      participants: 19234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=fed",
    },
    {

      id: 33,
      title: "Will inflation drop below 2% in the US by Q4 2026?",
      category: "Business",
      yesPrice: 48,
      noPrice: 52,
      volume: "$1.2M",
      endDate: "Dec 31, 2026",
      participants: 11234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=inflation",
    },
    {

      id: 34,
      title: "Will Amazon stock reach $300 in 2026?",
      category: "Business",
      yesPrice: 59,
      noPrice: 41,
      volume: "$1.6M",
      endDate: "Dec 31, 2026",
      participants: 13456,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=amazon",
    },
    {

      id: 35,
      title: "Will there be a US recession in 2026?",
      category: "Business",
      yesPrice: 37,
      noPrice: 63,
      volume: "$3.1M",
      endDate: "Dec 31, 2026",
      participants: 25678,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=recession",
    },
    {

      id: 36,
      title: "Will Apple become the first $5T company in 2026?",
      category: "Business",
      yesPrice: 52,
      noPrice: 48,
      volume: "$1.8M",
      endDate: "Dec 31, 2026",
      participants: 16789,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=apple5t",
    },
  ],
  tech: [
    {

      id: 37,
      title: "Will AI replace 50% of coding jobs by 2030?",
      category: "Tech",
      yesPrice: 38,
      noPrice: 62,
      volume: "$980K",
      endDate: "Dec 31, 2030",
      participants: 15234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=ai",
    },
    {

      id: 38,
      title: "Will SpaceX land humans on Mars by 2030?",
      category: "Tech",
      yesPrice: 23,
      noPrice: 77,
      volume: "$2.1M",
      endDate: "Dec 31, 2030",
      participants: 18765,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=spacex",
    },
    {

      id: 39,
      title: "Will Apple release AR glasses in 2026?",
      category: "Tech",
      yesPrice: 35,
      noPrice: 65,
      volume: "$450K",
      endDate: "Dec 31, 2026",
      participants: 5234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=apple",
    },
    {

      id: 40,
      title: "Will ChatGPT-5 be released in 2026?",
      category: "Tech",
      yesPrice: 71,
      noPrice: 29,
      volume: "$1.5M",
      endDate: "Dec 31, 2026",
      participants: 19876,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=chatgpt",
    },
    {

      id: 41,
      title: "Will quantum computers break RSA encryption by 2028?",
      category: "Tech",
      yesPrice: 26,
      noPrice: 74,
      volume: "$670K",
      endDate: "Dec 31, 2028",
      participants: 8901,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=quantum",
    },
    {

      id: 42,
      title: "Will self-driving cars be legal in all US states by 2027?",
      category: "Tech",
      yesPrice: 41,
      noPrice: 59,
      volume: "$1.3M",
      endDate: "Dec 31, 2027",
      participants: 14567,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=selfdriving",
    },
  ],
  climate: [
    {

      id: 43,
      title: "Will global temperatures rise by 1.5°C by 2027?",
      category: "Climate",
      yesPrice: 81,
      noPrice: 19,
      volume: "$1.5M",
      endDate: "Dec 31, 2027",
      participants: 6789,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=climate",
    },
    {

      id: 44,
      title: "Will renewable energy exceed 50% of US power by 2028?",
      category: "Climate",
      yesPrice: 56,
      noPrice: 44,
      volume: "$780K",
      endDate: "Dec 31, 2028",
      participants: 6543,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=renewable",
    },
    {

      id: 45,
      title: "Will Arctic sea ice reach a new record low in 2026?",
      category: "Climate",
      yesPrice: 69,
      noPrice: 31,
      volume: "$540K",
      endDate: "Sep 30, 2026",
      participants: 5432,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=arctic",
    },
    {

      id: 46,
      title: "Will a major country ban gas cars by 2028?",
      category: "Climate",
      yesPrice: 47,
      noPrice: 53,
      volume: "$890K",
      endDate: "Dec 31, 2028",
      participants: 8765,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=gasban",
    },
    {

      id: 47,
      title: "Will carbon capture technology scale to 1GT/year by 2030?",
      category: "Climate",
      yesPrice: 33,
      noPrice: 67,
      volume: "$670K",
      endDate: "Dec 31, 2030",
      participants: 7654,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=carbon",
    },
    {

      id: 48,
      title: "Will a Category 6 hurricane be created by 2027?",
      category: "Climate",
      yesPrice: 54,
      noPrice: 46,
      volume: "$720K",
      endDate: "Dec 31, 2027",
      participants: 6234,
      icon: "https://api.dicebear.com/7.x/shapes/svg?seed=hurricane",
    },
  ],
  all: [],
};

// Combine all markets for "All" category
marketsByCategory.all = [
  ...marketsByCategory.trending,
  ...marketsByCategory.new,
  ...marketsByCategory.sports,
  ...marketsByCategory.crypto,
  ...marketsByCategory.politics,
  ...marketsByCategory.business,
  ...marketsByCategory.tech,
  ...marketsByCategory.climate,
];
